### ISSUE TITLE
Does not evaluate Ocr text

### ISSUE THREAD

**Issue by MokshUpadhyay57** [scribeocr/scribeocr#31]
I am trying to use it, it recognize the text 
make the box around the words
but when i try to evaluate the ocr text, it does not do anything
![Screenshot from 2024-05-12 16-15-24](https://github.com/scribeocr/scribeocr/assets/68551326/25bfd8dc-e618-4ec6-b78c-2393a10d0ee0)
![Uploading Screenshot from 2024-05-12 16-15-24.png…]()

**Comment by Balearica** [comment]
The "Evaluate OCR data" feature was primarily added for debugging purposes, so was not documented.  I've added a page explaining how this feature works to the documentation site.  Let me know if that leaves any questions regarding what the feature does unanswered. 
https://docs.scribeocr.com/evaluate.html

Additionally, to streamline the interface I updated the site so that word error rate metrics are automatically calculated and displayed when you click "Set Ground Truth" (it previously required switching the display mode to `Evaluate Mode`).
