### ISSUE TITLE
use scribeocr in a project

### ISSUE THREAD

**Issue by Ana0112** [scribeocr/scribeocr#48]
Hello, thanks for this amazing project!

I have been using `tesseract.js` cdn in a website (hugo+webpack & netlify). 
I stumbled upon your work, and found that the OCR output is significantly better than what i get from the original tesseract.js !

Is there anyway to use scribeocr in my website - In browser?
Is it possible to deliver your forked tesseract.js over a cdn?

**Comment by Ana0112** [comment]
beginner question, why do we need to fire up a server when all the processing is being done in browser?

**Comment by Ana0112** [comment]
> Assuming you are talking about running the OCR code standalone in a browser-based application (without the interface UI), I will need to confirm that this can be done easily and get back to you.

ok great. Please do let me know about the standalone browser application. 
Been playing around with the code a bit, but getting stuck at worker import and webpack errors.
 


> This means that any software that uses it as a dependency would need to also be released as GPL licensed, or obtain a paid license.

Ok. How does this work? How to get a paid license? 

I am running a few custom algorithms in backend (using aws lambda api), if I choose the GPL license do I have to make that public as well? 

For GPL license, I guess I will have to make the repo public - that's about it? Backend (lambda) code is not on github though.

**Comment by Balearica** [comment]
> ok great. Please do let me know about the standalone browser application.
Been playing around with the code a bit, but getting stuck at worker import and webpack errors.

I spent some time reviewing, and I think a refactor is required to make Scribe OCR work as a library.  The primary issue at present is that many OCR-related functions engage directly with specific HTML elements in the GUI, which is not portable.  However, this is not a conceptually difficult thing to fix, so I should be able to implement in the near future.

> Ok. How does this work? How to get a paid license?
I am running a few custom algorithms in backend (using aws lambda api), if I choose the GPL license do I have to make that public as well?
For GPL license, I guess I will have to make the repo public - that's about it? Backend (lambda) code is not on github though.

For the [AGPL license](https://www.gnu.org/licenses/agpl-3.0.en.html), if you "convey a work based on the [AGPL-licensed] Program]", "You must license the entire work, as a whole, under [the AGPL license]".  This would include any front and back-end code that together constitutes a work based on Scribe OCR.  This does not include works that are independent/unrelated simply because they run on the same site.  For example, using proprietary code for analytics, ads, or another entirely unrelated feature does not constitute a violation.

For the proprietary license options, send an email to admin@scribeocr.com to discuss.  Include a short description of your program (including whether it is a user-facing application or library) and what Scribe OCR would be used for.

**Comment by Balearica** [comment]
It is now possible for developers to embed ScribeOCR recognition in their own applications.  The codebase has been split into 2 repos.  This repo contains code for the user interface, and a repo named [Scribe.js](https://github.com/scribeocr/scribe.js) contains the library code.  This library is published as `scribe.js-ocr` on `npm`, and instructions for how to use it along with examples are in that repo.  If anybody has questions/issues regarding how to use Scribe.js they should be asked in [that repo](https://github.com/scribeocr/scribe.js).
